<div style="display:block">
    <div style="width: 20%; display: inline-block; text-align: left;">
        <img src="http://upload.wikimedia.org/wikipedia/en/0/0c/Mu_Sigma_Logo.jpg" style="height:75px; margin-left:0px" />
    </div>
    <div style="width: 59%; display: inline-block">
        <h1  style="text-align: center">Analysis in Python</h1>
    </div>
    <div style="width: 20%; text-align: right; display: inline-block;">
        <div style="width: 100%; text-align: left; display: inline-block;">
            <i>Created: </i>
            <time datetime="2016-10-12" pubdate>October, 2016</time>
        </div>
    </div>

</div>

There a set of packages that enable analysis, let's have a look into them:
* Numpy: Numpy has functions that help us do numerical computing/ mathematical operations on **numpy arrays**. These arrays are are abstraction of lists
* Pandas: Pandas is used for data handling and manipulation. It creates and uses a special data structure called **dataframe**,which is similar to R dataframes
* Matplotlib: It has tools for visualizing the data
* Scikit-Learn:Scikit-learn is a package for data mining and data analysis. It has classes/functions for implementing various machine learning algorithms

## Numpy
Numpy contains core libraries for Numerical Computing. Numpy provides a multi-dimensional array, along with functions/tools for working with these arrays. <br>
Let's get started!

In [2]:
import numpy as np

NumPy’s main object is the homogeneous multidimensional array. These are called **ndarrays**. They are abstraction of Python lists. So why use these arrays? Because lists are not meant for analysis! They have very efficient storage and retrieval mechanisms but that's all there's to it. When we need numerical power like vectorization, lists are not best suited, that's where arrays come in.<br>

Lets start by creating arrays. The easiest form is to create it from lists

In [4]:
a = np.array(['Harsha','Varun','Jatan'])
print a
print type(a)

['Harsha' 'Varun' 'Jatan']
<type 'numpy.ndarray'>


There are eeasier and quicker ways to create an array 

In [12]:
print np.arange(1,10,2) #Similar to range, but generates arrays instead
print "\n"
print np.zeros((2,5)) # Produces an array of 0s of the desired shape
print "\n"
print np.ones((2,5)) # Produces an array of 1s of the desired shape
print "\n"
print np.empty((2,5)) # Produces an empty array of the desired shape

[1 3 5 7 9]


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


We have used used something called **shape** earlier. What exactly is it? Shape indicates the dimensions of the array. Imagine an array as an matrix. We define the matrix by its dimensions rows\*columns, and if scale this to ndimensions, we get an ndarray. <br>

Now let's look at the properties for an ndarray.

In [15]:
print a.shape
print "\n"
print a.ndim
print "\n"
print a.size
print "\n"
print a.dtype
print "\n"
print a.itemsize

(3L,)


1


3


|S6


6


**Indexing an array** Let's start off by indexing a 1d array

In [16]:
a = np.array ([1, 1, 2, 3, 5, 8, 13, 21])
print(a[0])
print(a[4])

1
5


Now, let's try the same for multi-dimensional arrays. Please note how we define ndarrays. A 1d array can be imagined and instantiated using a simple list and similarly, using the same analogy, an ndarray is a list of lists

In [17]:
b = np.array([ [[111, 112],  [121, 122]],[[211, 212],  [221, 222]],[[311, 312],  [321, 322]]])

print b.shape

print(b[0][1][0])

print(b[1][1][1])

(3L, 2L, 2L)
121
222


Arrays can also be indexed using arrays! 

In [26]:
a = np.array([ 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144])
i = np.array( [ 1, 1, 3, 8, 5] ) 
print a[i]
i = np.array([[3,4], [9,7 ]])
print a[i]

[ 4  4 16 81 36]
[[ 16  25]
 [100  64]]


We can also use slicing operations on the arrays to get a "view" of the original array. General sytax for slicing is array[start:stop:step]. Let's look at an example below using the same array that we created earlier

In [23]:
print a[2:5]
print b[1:2,0:2,0:2]

[ 9 16 25]
[[[211 212]
  [221 222]]]


**Note**: indexing on lists and tuples create new objects, a slicing operation on an array creates a view on the original array. So we get an another possibility to access the array, or better a part of the array. From this follows that if we modify a view, the original array will be modified as well. We have to the **copy** function if we want to create a copy of the original array

In [28]:
c =  a[2:5]
print a
c[0] = 1
print a
print"\n"
a = np.array([ 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144])
c =  a[2:5].copy()
c[0] = 1
print a

[  1   4   9  16  25  36  49  64  81 100 121 144]
[  1   4   1  16  25  36  49  64  81 100 121 144]


[  1   4   9  16  25  36  49  64  81 100 121 144]


Now let us look into computations using arrays. We can add, subtract and multiply arrays. These operations will be applied element wise 

In [24]:
a = np.array( [ 120,500,502,8796,2334] )
b = np.array( [ 454,43,5,333,46] )
print a+b
print a-b

c = np.array( [ 1, 1, 0, 1,0] )
print (a+b)*c

[ 574  543  507 9129 2380]
[-334  457  497 8463 2288]
[ 574  543    0 9129    0]


Till now we have done additions and multiplication of the same shaped arrays. What if we do for arrays of different dimensions?

In [10]:
a = np.array( [ 120,500,502,8796] )
b = np.array( [ [454],[43],[5]] )
print a+b
print a*b

[[ 574  954  956 9250]
 [ 163  543  545 8839]
 [ 125  505  507 8801]]
[[  54480  227000  227908 3993384]
 [   5160   21500   21586  378228]
 [    600    2500    2510   43980]]


The array a and b got replicated across the dimensions to form a 4x3 array and then the operation happened. This is called **broadcasting**. Note that broadcasting only happens only in a dimension when the size of one of them is 1.<br>
For example you can broadcast a 3\*1 and and 1\*2 to get a 3\*2 array, but we can't broadcast when there are a 3\*1 and 2\*2 array 


In [4]:
a = np.array( [ 120,500,502] ) #3, array
b = np.array( [ [454],[43]] ) # 2*1 array
print a+b
print a*b

a = np.array( [ 120,500,502,8796] ) #3, array
b = np.array( [ [454,1],[43,2]] ) # 2*2 array


[[574 954 956]
 [163 543 545]]
[[ 54480 227000 227908]
 [  5160  21500  21586]]


ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

Now let's see what all transformations we can perform on an array

In [38]:
a = np.array( [ 120,500,502,8796,100,10,40,1202] )
a.sort() #Sorts the array. Sorting is inplace
print a

print a.reshape(4,2) #Change the dimensions. Only works when the number of elements match. Returns a new array, not inplace

a.resize(5,2) #Changes the shape, but inplace. Doesn't require the elements to match
print a

a = a.flatten() #Collapses the array into 1d
print a

b = np.array([[1, 2], [3, 4]])
c = np.array([[5, 6]])
print np.concatenate((b, c), axis=0) #Adds new row, returns a new array
print np.concatenate((b, c.T), axis=1) #Adds new columns, returns a new array

a = np.arange(10)
print a
print np.clip(a,1,8) # all the values >8 and <1 will be replaced with 8 and 1 respectively

[  10   40  100  120  500  502 1202 8796]
[[  10   40]
 [ 100  120]
 [ 500  502]
 [1202 8796]]
[[  10   40]
 [ 100  120]
 [ 500  502]
 [1202 8796]
 [   0    0]]
[  10   40  100  120  500  502 1202 8796    0    0]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[0 1 2 3 4 5 6 7 8 9]
[1 1 2 3 4 5 6 7 8 8]


We can also loop through arrays just like lists. Note that for multidimensional arrays, iteration proceeds over the first axis such that each loop returns a subsection of the array

In [39]:
for i in a:
    print i
print "\n"
a = np.array([[1, 2], [3, 4], [5, 6]])
for (x,y) in a:
    print x*y

0
1
2
3
4
5
6
7
8
9


2
12
30


Arrays of equal dimensions can also be compared to each other

In [41]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
print a > b # Returns an array
print "\n"
print np.any(a>b) # Returns true if any element of a > b. Element wise comparision
print "\n"
print np.all(a>b) # Returns true if all elements of a > b. Element wise comparision
print "\n"
print np.where(a>b,a,b) #Returns elements, either from a or b, depending on condition
print "\n"
a[0] = np.nan
print np.isnan(a) #Test element-wise for NaN and return result as a boolean array
print "\n"
print np.isfinite(a) #Test element-wise if it is finite and return result as a boolean array
print "\n"

[ True False False]


True


False


[ 1.  3.  2.]


[ True False False]


[False  True  True]




Now let's do some basic univariate analysis on our array. We'll try computing the summary statistics

In [47]:
a = np.array( [ 120,500,502,8796,100,10,40,1202] )
print a.mean()
print "\n"
print a.var()
print "\n"
print a.std()
print "\n"
print np.median(a)
print "\n"
b = np.arange(8)
print np.cov(a,b)
print "\n"
print np.corrcoef(a,b)

1408.75


7933238.9375


2816.60059957


310.0


[[  9.06655879e+06  -3.49857143e+02]
 [ -3.49857143e+02   6.00000000e+00]]


[[ 1.         -0.04743445]
 [-0.04743445  1.        ]]
